version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target:/usr/src/app/target            # Монтируем каталог 'target' внутрь контейнера при запуске контейнера